# Generated by Django 5.1 on 2024-08-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_project',
            field=models.CharField(default='', max_length=255),
        ),
    ]
