# Generated by Django 5.1 on 2024-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_detail_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail_project',
            field=models.TextField(),
        ),
    ]
