# Generated by Django 5.1 on 2024-08-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_detail_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', upload_to='project/photo/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='project/covers/%Y/%m/%d'),
        ),
    ]
