# Generated by Django 5.1 on 2024-08-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_project_link_alter_project_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_git',
            field=models.CharField(blank=True, default='', max_length=65),
        ),
    ]
